# See https://github.com/dart-lang/mono_repo for details
dart:
  - dev

stages:
  - analyzer_and_format:
    - dartfmt
    - dartanalyzer: --fatal-infos --fatal-warnings .
#  - unit_test:
#    - test
