# See https://pub.dev/packages/mono_repo for details
stages:
  - analyzer_and_format:
    - group:
      - format
      - analyze: --fatal-infos --fatal-warnings .
      dart: dev
    - group:
      - analyze: --fatal-warnings .
      dart: [2.12.0]

cache:
  directories:
    - .dart_tool/build
    - .dart_tool/pub
