branches:
  only:
    - master

version: '1.0.{build}'

install:
  - ps: wget https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-windows-x64-release.zip -OutFile dart-sdk.zip
  - cmd: echo "Unzipping dart-sdk..."
  - cmd: 7z x dart-sdk.zip -o"C:\tools" -y > nul
  - set PATH=%PATH%;%APPDATA%\Pub\Cache\bin
  - cd webdev
  - C:\tools\dart-sdk\bin\pub.bat get && exit 0

build: off

test_script:
  - C:\tools\dart-sdk\bin\pub.bat run test -j 1

cache:
  - C:\Users\appveyor\AppData\Roaming\Pub\Cache
