# See https://github.com/dart-lang/mono_repo for details
stages:
  - analyzer_and_format:
    - group:
      - dartfmt
      - dartanalyzer: --fatal-infos --fatal-warnings .
      dart: 2.8.0-dev.10.0
