# See https://pub.dev/packages/mono_repo for details
os:
  - windows
  - linux

stages:
  - analyzer_and_format:
    - group:
      - format
      - analyze: --fatal-infos .
      dart: dev
    - test:
      dart:
        - stable
        - dev