name: webdev_example_app
description: A web app example for webdev CLI.
version: 0.0.1

environment:
  sdk: ">=2.0.0-dev.3.0 <2.0.0"

dependencies:
  angular: ^5.0.0-alpha+3
  browser: ^0.10.0

dev_dependencies:
  webdev:
    path: ../
  ##############################################################################
  # Temporary until build_runner exposes a function to generate it's script.
  build_runner:
    git:
      url: https://github.com/dart-lang/build.git
      path: build_runner
  ##############################################################################

dependency_overrides:
  # Necessary with angular: ^5.0.0-alpha+1 dependency.
  analyzer: ^0.31.0-alpha.1
