targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          dart2js_args:
            - -O4 
            - --csp
        generate_for:
          - web/**.dart
      extension|client_js_copy_builder:
        enabled: true
      
builders:
  client_js_copy_builder:
    import: "tool/copy_builder.dart"
    builder_factories:
        - copyBuilder
    build_extensions:
      {
        "web/{{}}.dart.js": ["build/web_prod/{{}}.js"],
        "web/{{}}.png": ["build/web_prod/{{}}.png"],
        "web/{{}}.html": ["build/web_prod/{{}}.html"],
        "web/{{}}.css": ["build/web_prod/{{}}.css"],
        "web/manifest_prod.json": ["build/web_prod/manifest_prod.json"],
        "web/panel.js": ["build/web_prod/panel.js"],
        "web/detector.js": ["build/web_prod/detector.js"],
        "web/devtools.js": ["build/web_prod/devtools.js"],
      }
    auto_apply: none
    build_to: source
