targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          dart2js_args:
            - -O4 # Note: Change to -01 for unminified JS. 
            - --csp
        generate_for:
          - web/**.dart
      extension|client_js_copy_builder:
        enabled: true
      
builders:
  client_js_copy_builder:
    import: "tool/copy_builder.dart"
    builder_factories:
        - copyBuilder
    build_extensions:
      {
        "web/{{}}.dart.js": ["prod_build/{{}}.js"],
        "web/{{}}.png": ["prod_build/{{}}.png"],
        "web/{{}}.html": ["prod_build/{{}}.html"],
        "web/{{}}.css": ["prod_build/{{}}.css"],
        "web/manifest.json": ["prod_build/manifest.json"],
        "web/panel.js": ["prod_build/panel.js"],
        "web/detector.js": ["prod_build/detector.js"],
        "web/devtools.js": ["prod_build/devtools.js"],
      }
    auto_apply: none
    build_to: source
