targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          dart2js_args:
            - -O1 # Note: Change to -04 for minified JS. 
            - --csp
        generate_for:
          - web/**.dart
      mv3_extension|client_js_copy_builder:
        enabled: true
      
builders:
  client_js_copy_builder:
    required_inputs: [".js", ".png", ".html", ".css", ".json"]
    import: "tool/copy_builder.dart"
    builder_factories:
        - copyBuilder
    build_extensions:
      {
        "web/{{}}.dart.js": ["compiled/{{}}.dart.js"],
        "web/static_assets/{{}}.png": ["compiled/static_assets/{{}}.png"],
        "web/static_assets/{{}}.html": ["compiled/static_assets/{{}}.html"],
        "web/static_assets/{{}}.css": ["compiled/static_assets/{{}}.css"],
        "web/manifest.json": ["compiled/manifest.json"],
      }
    auto_apply: none
    build_to: source
