include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  exclude:
    # Ignore generated files
    - "lib/data/*"
    # Ignore debug extension builds
    - "debug_extension/compiled/*"

linter:
  rules:
    - always_use_package_imports
