include: package:analysis_config/analysis_options.yaml

analyzer:
  exclude:
    # Ignore generated files
    - "lib/data/*"
    # Ignore debug extension builds
    - "debug_extension/compiled/*"
    # Ignore integration tests
    - "test/integration/**"

linter:
  rules:
    - always_use_package_imports
