# This file contains the analysis options used for code in the webdev
# repository.

analyzer:
  exclude:
      # Ignore generated files
    - "lib/data/*"

linter:
  rules:
    - prefer_final_locals

