# This file contains the analysis options used for code in the webdev
# repository.

include: package:lints/recommended.yaml

analyzer:
  exclude:
    # Ignore generated files
    - "lib/data/*"
    # Ignore debug extension builds
    - "debug_extension/dev_build/*"
    - "debug_extension/prod_build/*"
    - "debug_extension_mv3/dev_build/*"
    - "debug_extension_mv3/prod_build/*"

linter:
  rules:
    - always_use_package_imports
    - avoid_void_async
    - directives_ordering
    - prefer_final_locals
    - require_trailing_commas
    - unawaited_futures
    - unnecessary_lambdas

# TODO(elliette): Enable commented out rules.
dart_code_metrics:
  metrics:
    # cyclomatic-complexity: 20
    # number-of-parameters: 5
    # maximum-nesting-level: 5
  metrics-exclude:
    - test/**
  rules:
    - avoid-cascade-after-if-null
    - avoid-collection-methods-with-unrelated-types
    - avoid-duplicate-exports
    - avoid-global-state  
    - avoid-missing-enum-constant-in-map
    - avoid-nested-conditional-expressions
    - avoid-non-ascii-symbols
#    - avoid-non-null-assertion
#    - avoid-passing-async-when-sync-expected
#    - avoid-throw-in-catch-block

    - avoid-top-level-members-in-tests
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - binary-expression-operand-order
    - double-literal-format
 #    - format-comment
 #    - member-ordering
    - no-boolean-literal-compare
#    - no-empty-block ENABLE
    - no-equal-then-else
 #   - prefer-async-await
 #   - prefer-commenting-analyzer-ignores
 # STOPPED HERE
  #  - prefer-conditional-expressions Too many false positives involving large conditional expressions.
  #  - prefer-correct-identifier-length Too many false positives with fine names like i and id.
  #  - prefer-correct-test-file-name TODO(jacobr): enable and fix violations.
    - prefer-correct-type-name
  #  - prefer-enums-by-name Cannot able unless lint adds a special case for orElse
  #  - prefer-first TODO(jacobr): enable as a follow up PR.
  #  - prefer-immediate-return TODO(jacobr): enable as a follow up PR.
    - prefer-iterable-of
    - prefer-last
    # - prefer-match-file-name
    # TODO(jacobr): consider enabling or enabling to periodically audit.
    # This one has a lot of false positives but is also quite nice.
    # - prefer-moving-to-variable:
    #    allowed-duplicated-chains: 2
    # - prefer-static-class
    # TODO(jacobr): enable this one as a follow up CL. This one has a lot
    # of violations but generally the style is aligned with DevTools.
    # - prefer-trailing-comma
    - tag-name
    - always-remove-listener
    # - avoid-border-all Micro-optimization to avoid a const constructor.
    # - avoid-returning-widgets  This one is nice but has a lot of false positives.
    - avoid-shrink-wrap-in-lists
    - avoid-unnecessary-setstate
    - avoid-expanded-as-spacer
    - avoid-wrapping-in-padding
    - check-for-equals-in-render-object-setters
    - consistent-update-render-object
    # - prefer-const-border-radius TODO(jacobr): enable.
    - prefer-correct-edge-insets-constructor
    # - prefer-extracting-callbacks I'm not clear this is always a good idea. Seems like a workaround.
    # - prefer-single-widget-per-file
    - prefer-using-list-view