# See https://github.com/dart-lang/mono_repo for details
dart:
  - be/raw/latest

stages:
  - analyzer_and_format:
    - group:
      - dartfmt
      - dartanalyzer: --fatal-infos --fatal-warnings .
  - unit_test:
    - test:
