# See https://github.com/dart-lang/mono_repo for details
dart:
  - 2.1.0
  - dev

stages:
  - analyzer_and_format:
    - group:
      - dartfmt
      - dartanalyzer: --fatal-infos --fatal-warnings .
      dart: dev
    - group:
      - dartanalyzer: --fatal-warnings .
      dart: [2.1.0]
  - unit_test:
    - test:
