# See https://pub.dev/packages/mono_repo for details
stages:
  - analyzer_and_format:
    - group:
      - format
      - analyze: --fatal-infos .
      - test: test/build/ensure_version_test.dart
      dart: dev
    - group:
      - analyze: .
      - test: test/build/min_sdk_test.dart --run-skipped
      dart: stable
  - unit_test:
    - group:
      - command: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - test:
      dart:
        - dev
        - stable
    - test:
      os: windows
      dart:
        - dev
        - stable
  - beta_cron:
    - analyze: .
      dart: beta
    - group:
      - command: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - test: -j 1
      dart: beta
    - test: -j 1
      os: windows
      dart: beta
