# See https://github.com/dart-lang/mono_repo for details
dart:
  - 2.6.0
  - stable

stages:
  - analyzer_and_format:
    - group:
      - dartfmt
      - dartanalyzer: --fatal-infos --fatal-warnings .
      dart: dev
    - group:
      - dartanalyzer: --fatal-warnings .
      dart: [2.6.0]
  - unit_test:
    - test:
    - test:
      os: windows
      dart: stable
