# See https://github.com/dart-lang/mono_repo for details
dart:
  - dev/raw/2.2.1-dev.1.0

stages:
  - analyzer_and_format:
    - group:
      - dartfmt
      - dartanalyzer: --fatal-infos --fatal-warnings .
  - unit_test:
    - test:
