# See https://github.com/dart-lang/mono_repo for details
dart:
  - dev
  - stable

stages:
  - analyzer_and_format:
    - group:
      - dartfmt
      - dartanalyzer: --fatal-infos --fatal-warnings .
      - test: test/build/ensure_version_test.dart
      dart: dev
    - group:
      - dartanalyzer: --fatal-warnings .
      dart: [dev]
  - unit_test:
    - test:
    - test:
      os: windows
      dart: stable
