# See https://pub.dev/packages/mono_repo for details
stages:
  - analyzer_and_format:
    - group:
      - dartfmt
      - dartanalyzer: --fatal-infos --fatal-warnings .
      - test: test/build/ensure_version_test.dart
      dart: dev
    - group:
      - dartanalyzer: --fatal-warnings .
      dart: [2.10.0]
  - unit_test:
    - test: -x expression-compilation-service
      dart: 2.10.0
    - test:
      dart: dev
    - test: -x expression-compilation-service
      os: windows
      dart: 2.10.0
    - test:
      os: windows
      dart: dev
