targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          compiler: dart2js
          dart2js_args:
            - -O0
        generate_for:
          - web/client.dart
      webdev|client_js_copy_builder:
        enabled: true

builders:
  client_js_copy_builder:
    import: "tool/copy_builder.dart"
    builder_factories:
        - copyBuilder
    build_extensions:
      web/client.dart.js:
        - lib/src/serve/injected/client.js
    auto_apply: none
    build_to: source
