# See https://github.com/dart-lang/mono_repo for details
dart:
  - stable
  - 2.3.2-dev.0.1

stages:
  - analyzer_and_format:
    - group:
      - dartfmt
      - dartanalyzer: --fatal-infos --fatal-warnings .
      dart: dev
    - group:
      - dartanalyzer: --fatal-warnings .
      dart: [2.3.2-dev.0.1]
  - unit_test:
    - test: -j 1
