# See https://github.com/dart-lang/mono_repo for details
dart:
  - dev
  - 2.3.0

stages:
  - analyzer_and_format:
    - group:
      - dartfmt
      - dartanalyzer: --fatal-infos --fatal-warnings .
      dart: dev
    - group:
      - dartanalyzer: --fatal-warnings .
      dart: [2.3.0]
  - unit_test:
    - test: -j 1 --run-skipped
