# See https://github.com/dart-lang/mono_repo for details
dart:
  - 2.1.1-dev.3.2

stages:
  - analyzer_and_format:
    - dartfmt
    - dartanalyzer: --fatal-infos --fatal-warnings .
  - unit_test:
    - test: -j 1
