# See https://github.com/dart-lang/mono_repo for details
dart:
  - stable
  - 2.5.0

stages:
  - analyzer_and_format:
    - group:
      - dartfmt
      - dartanalyzer: --fatal-infos --fatal-warnings .
      - test: test/build/ensure_build_test.dart
      dart: dev
    - group:
      - dartanalyzer: --fatal-warnings .
      dart: [2.5.0]
  - unit_test:
    - test: -j 1
    - test: -j 1
      os: windows
      dart: stable
