# See https://pub.dev/packages/mono_repo for details
stages:
  - analyzer_and_format:
    - group:
      - format
      - analyze: --fatal-infos .
      - test: test/build/ensure_build_test.dart
      sdk: stable
    - group:
      - analyze: .
      sdk: stable
  - unit_test:
    - group:
      - command: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - test: -j 1
      sdk:
        - stable
    - test: -j 1
      os: windows
      sdk:
        - stable

