# See https://github.com/dart-lang/mono_repo for details
dart:
  - dev
  - stable

stages:
  - analyzer_and_format:
    - group:
      - dartfmt
      - dartanalyzer: --fatal-infos --fatal-warnings .
  - unit_test:
    - test: -j 1 -x requires-edge-sdk --run-skipped
    - test: -t requires-edge-sdk --run-skipped
      dart:
        - be/raw/latest
