# Created with package:mono_repo v6.7.1
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
  DISPLAY: ":99"
permissions: read-all

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: stable
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 6.7.1
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "analyzer_and_format; linux; Dart dev; PKG: dwds_test_common/fixtures/_webdev_smoke; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:dwds_test_common/fixtures/_webdev_smoke;commands:format-analyze_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:dwds_test_common/fixtures/_webdev_smoke
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: dwds_test_common_fixtures__webdev_smoke_pub_upgrade
        name: dwds_test_common/fixtures/_webdev_smoke; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: dwds_test_common/fixtures/_webdev_smoke
      - name: "dwds_test_common/fixtures/_webdev_smoke; dart format --output=none --set-exit-if-changed ."
        run: "dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.dwds_test_common_fixtures__webdev_smoke_pub_upgrade.conclusion == 'success'"
        working-directory: dwds_test_common/fixtures/_webdev_smoke
      - name: "dwds_test_common/fixtures/_webdev_smoke; dart analyze --fatal-infos ."
        run: dart analyze --fatal-infos .
        if: "always() && steps.dwds_test_common_fixtures__webdev_smoke_pub_upgrade.conclusion == 'success'"
        working-directory: dwds_test_common/fixtures/_webdev_smoke
  job_003:
    name: "analyzer_and_format; linux; Dart dev; PKG: webdev; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos .`, `dart test test/build/ensure_build_test.dart`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:webdev;commands:format-analyze_0-test_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:webdev
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: webdev_pub_upgrade
        name: webdev; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: webdev
      - name: "webdev; dart format --output=none --set-exit-if-changed ."
        run: "dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.webdev_pub_upgrade.conclusion == 'success'"
        working-directory: webdev
      - name: "webdev; dart analyze --fatal-infos ."
        run: dart analyze --fatal-infos .
        if: "always() && steps.webdev_pub_upgrade.conclusion == 'success'"
        working-directory: webdev
      - name: webdev; dart test test/build/ensure_build_test.dart
        run: dart test test/build/ensure_build_test.dart
        if: "always() && steps.webdev_pub_upgrade.conclusion == 'success'"
        working-directory: webdev
  job_004:
    name: "unit_test; linux; Dart dev; PKG: webdev; `Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &`, `dart test -j 1`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:webdev;commands:command-test_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:webdev
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: webdev_pub_upgrade
        name: webdev; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: webdev
      - name: "webdev; Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &"
        run: "Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &"
        if: "always() && steps.webdev_pub_upgrade.conclusion == 'success'"
        working-directory: webdev
      - name: "webdev; dart test -j 1"
        run: dart test -j 1
        if: "always() && steps.webdev_pub_upgrade.conclusion == 'success'"
        working-directory: webdev
    needs:
      - job_001
      - job_002
      - job_003
  job_005:
    name: "unit_test; linux; Dart main; PKG: webdev; `Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &`, `dart test -j 1`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:main;packages:webdev;commands:command-test_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:main;packages:webdev
            os:ubuntu-latest;pub-cache-hosted;sdk:main
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: main
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: webdev_pub_upgrade
        name: webdev; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: webdev
      - name: "webdev; Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &"
        run: "Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &"
        if: "always() && steps.webdev_pub_upgrade.conclusion == 'success'"
        working-directory: webdev
      - name: "webdev; dart test -j 1"
        run: dart test -j 1
        if: "always() && steps.webdev_pub_upgrade.conclusion == 'success'"
        working-directory: webdev
    needs:
      - job_001
      - job_002
      - job_003
  job_006:
    name: "unit_test; windows; Dart dev; PKG: webdev; `dart test -j 1`"
    runs-on: windows-latest
    steps:
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: webdev_pub_upgrade
        name: webdev; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: webdev
      - name: "webdev; dart test -j 1"
        run: dart test -j 1
        if: "always() && steps.webdev_pub_upgrade.conclusion == 'success'"
        working-directory: webdev
    needs:
      - job_001
      - job_002
      - job_003
  job_007:
    name: "unit_test; windows; Dart main; PKG: webdev; `dart test -j 1`"
    runs-on: windows-latest
    steps:
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: main
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: webdev_pub_upgrade
        name: webdev; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: webdev
      - name: "webdev; dart test -j 1"
        run: dart test -j 1
        if: "always() && steps.webdev_pub_upgrade.conclusion == 'success'"
        working-directory: webdev
    needs:
      - job_001
      - job_002
      - job_003
  job_008:
    name: "beta_cron; linux; Dart beta; PKG: webdev; `Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &`, `dart test -j 1`"
    runs-on: ubuntu-latest
    if: "github.event_name == 'schedule'"
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:beta;packages:webdev;commands:command-test_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:beta;packages:webdev
            os:ubuntu-latest;pub-cache-hosted;sdk:beta
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: beta
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: webdev_pub_upgrade
        name: webdev; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: webdev
      - name: "webdev; Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &"
        run: "Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &"
        if: "always() && steps.webdev_pub_upgrade.conclusion == 'success'"
        working-directory: webdev
      - name: "webdev; dart test -j 1"
        run: dart test -j 1
        if: "always() && steps.webdev_pub_upgrade.conclusion == 'success'"
        working-directory: webdev
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
      - job_005
      - job_006
      - job_007
  job_009:
    name: "beta_cron; linux; Dart beta; PKG: webdev; `dart analyze .`"
    runs-on: ubuntu-latest
    if: "github.event_name == 'schedule'"
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:beta;packages:webdev;commands:analyze_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:beta;packages:webdev
            os:ubuntu-latest;pub-cache-hosted;sdk:beta
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: beta
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: webdev_pub_upgrade
        name: webdev; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: webdev
      - name: webdev; dart analyze .
        run: dart analyze .
        if: "always() && steps.webdev_pub_upgrade.conclusion == 'success'"
        working-directory: webdev
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
      - job_005
      - job_006
      - job_007
  job_010:
    name: "beta_cron; windows; Dart beta; PKG: webdev; `dart test -j 1`"
    runs-on: windows-latest
    if: "github.event_name == 'schedule'"
    steps:
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: beta
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: webdev_pub_upgrade
        name: webdev; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: webdev
      - name: "webdev; dart test -j 1"
        run: dart test -j 1
        if: "always() && steps.webdev_pub_upgrade.conclusion == 'success'"
        working-directory: webdev
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
      - job_005
      - job_006
      - job_007
  job_011:
    name: Notify failure
    runs-on: ubuntu-latest
    if: "(github.event_name == 'push' || github.event_name == 'schedule') && failure()"
    steps:
      - run: |
          curl -H "Content-Type: application/json" -X POST -d \
            "{'text':'Build failed! ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}'}" \
            "${CHAT_WEBHOOK_URL}"
        env:
          CHAT_WEBHOOK_URL: "${{ secrets.BUILD_AND_TEST_TEAM_CHAT_WEBHOOK_URL }}"
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
      - job_005
      - job_006
      - job_007
      - job_008
      - job_009
      - job_010
